---
version: '3.3'
services:

  mongo-client:
    container_name: mongo-client
    image: mvertes/alpine-mongo
    ports:
      - "27017"
    environment:
      - MONGO_PORT=5100
    networks:
      - broker_mynet

  client-discovery:
    container_name: client-discovery
    ports:
      - "5000:5000"
    build:
      context: ../../
      dockerfile: examples/Dockerfile
    depends_on:
      - mongo-client
    volumes:
      - ../../:/app/p2prpc/
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo-client
      - BOOKKEEPER_PORT=5000
      - APP_ROLES=client
      - DISCOVERY_FILE=/app/p2prpc/examples/client/network_discovery_client.txt
      - PASSWORD="super secret password"
      - SERVICE_NAME=client
      - SERVICE_PORT=4999
    command:
      - bash
      - -c
      - |
        cd /app/p2prpc
        export PYTHONPATH=$$PYTHONPATH:./
        python ./p2prpc/bookkeeper_service.py service &
        python ./p2prpc/bookkeeper_service.py update
    networks:
      - broker_mynet

  client:
    container_name: client
    ports:
      - "4999:4999"
    build:
      context: ../../
      dockerfile: examples/Dockerfile
    depends_on:
      - mongo-client
      - client-discovery
    volumes:
      - ../../:/app/p2prpc/
    environment:
      - MONGO_PORT=27017
      - MONGO_HOST=mongo-client
    command:
      - bash
      - -c
      - |
        cd /app/p2prpc
        export PYTHONPATH=$$PYTHONPATH:./
        python ./examples/client/client.py
    networks:
      - broker_mynet

networks:
  broker_mynet:
    external: true
# sudo docker-compose -f client.docker-compose.yml up